# Generated by Django 6.1.1 on 2026-09-21 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='titre')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('summary', models.TextField(verbose_name='résumé')),
                ('content', models.TextField(verbose_name='contenu')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/')),
                ('original_image', models.CharField(blank=True, editable=False, max_length=255, verbose_name='image du site original')),
                ('image_alt', models.CharField(blank=True, max_length=250, verbose_name='description de l’image')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='catégorie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='à la une')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
            ],
            options={
                'verbose_name': 'actualité',
                'verbose_name_plural': 'actualités',
                'ordering': ['-is_featured', '-published_at', '-pk'],
            },
        ),
    ]
