# Generated by Django 6.1.1 on 2026-09-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_featured', 'display_order', '-published_at', '-pk'], 'verbose_name': 'actualité', 'verbose_name_plural': 'actualités'},
        ),
        migrations.AddField(
            model_name='news',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ordre d’affichage'),
        ),
    ]
